version: '3.8'

services:
  client:
    build: 
      context: ./timetrackerwebapp.client
      dockerfile: Dockerfile
      args:
        - VITE_APP_API_BASE_URL=http://crow.ommat.ru/api
    environment:
      - VITE_APP_API_BASE_URL=http://crow.ommat.ru/api
    restart: always
    ports:
      - '3000:80'
    env_file:
      - .env