name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./timetrackerwebapp.client
        file: ./timetrackerwebapp.client/Dockerfile
        push: true
        tags: ghcr.io/nikizhu1/timetrackerwebapp-client:latest
        build-args: |
          REACT_APP_API_BASE_URL=https://crow.ommat.ru/api
